### ISSUE TITLE
Add journal activity when performing actions on a pull requests

### ISSUE THREAD

**Issue by xel1045** [eXolnet/redmine-pulls#11]
We need to keep track of the actions performed on a pull requests.

- [x] Issue relation is added
- [x] Issue relation is deleted
- [x] Pull request is merged
- [x] Pull request is closed
- [x] Pull request is reopen
- [x] Pull request's head branch is deleted
- [x] Pull request's head branch is restored
- [ ] ~Review is requested to a user~
- [ ] ~Reviewer accept changes~
- [ ] ~Reviewer request changes~

**Comment by martinblanchette** [comment]
@xel1045

After investigation, it would be difficult to use the event logging system from the Redmine codebase. First, this system is badly coupled with the concept of `Issue`. Moreover, with the current system and for certain types of action, it is impossible to form a combination describing the action properly.

So, I suggest removing the following 3 items from this post:
* Review is requested to a user
* Reviewer accept changes
* Reviewer request changes

Finally, I propose to create another post with the objective of refactor the Redmine codebase in order to be able to customize and manipulate journal and its details more easily for:
* improve description when restoring HEAD branch, use a better journal description as:
* journalize when review is requested to a user
* journalize when a reviewer accept changes
* journalize when a reviewer request changes

**Comment by xel1045** [comment]
You suggestion make sense for me. You can go ahead and split this issue in three. I'll create a PR with the notifications added for now.
